
#ifndef CORRUPT_INCLUDE_H_
#define CORRUPT_INCLUDE_H_

#define CORRUPT_VERSION_MAJOR "A"
#define CORRUPT_VERSION_MINOR "1"
#define CORRUPT_VERSION_PATCH "0"

#define CORRUPT_VERSION CORRUPT_VERSION_MAJOR "." CORRUPT_VERSION_MINOR "-" CORRUPT_VERSION_PATCH

#define CORRUPT_CONFIGURATION_FILE "assets/config.json"

#endif // CORRUPT_INCLUDE_H_

